# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.v1.64.jsonschema.json

run:
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - unused

linters-settings:
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - third_party
    - builtin
    - examples
